name: Build and Deploy Docs
on:
    push:
        branches:
            - '*'
        #- [main]
    release:
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    docs:
        name: Deploy Documentation

        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: 16
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Build Docs
              run: npm docs

            # - name: TSDoc Action
            #   uses: erikyo/tsdoc-action@v1
            #   with:
            #         source_dir: ./src/*
            #         entryPoints: ./src/index.ts
            #         entryPointStrategy: expand
            #         excludePrivate: true
            #         excludeProtected: true
            #         excludeExternals: true
            #         excludeInternal: true
            # with:
            #   source_dir: ./src/*
            #   githubPages: true
            #   output_dir: ./docs
            #   front_page: README.md

            - name: Deploy
              uses:
                  peaceiris/actions-gh-pages@v4
                  # If you're changing the branch from main,
                  # also change the `main` in `refs/heads/main`
                  # below accordingly.
                  #i f: github.ref == 'refs/heads/main'
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
